name: flutter_api_manager
description: APIManager-Flutter is a flutter library that can manage the API calls from a single place.
version: 0.0.1
homepage: https://github.com/101Loop/APIManager-Flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  mime: ^1.0.1
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
