name: flutter_api_manager
description: APIManager-Flutter is a flutter library that can manage the API calls from a single place.
version: 0.0.1
homepage: https://github.com/101Loop/APIManager-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  flutter_secure_storage: ^3.3.4
  mime: ^0.9.7
  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
