name: flutter_api_manager
description: APIManager-Flutter is a flutter library that can manage the API calls from a single place.
version: 1.0.0
homepage: https://github.com/101Loop/APIManager-Flutter

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  mime: ^1.0.1
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
